server:
  port: 9002

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaomingxian/cloud_config_github.git  #git clone的地址

#访问方式
# http://localhost:9002/application-test.yml
# http://localhost:9002/application-dev.yml
# http://localhost:9002/master/application-dev.yml
# http://localhost:9002/application/dev/master
# http://localhost:9002/master/application-dev
#