server:
  port: 9002

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hellxz/SpringCloudlearn
          search-paths: config-repo
          username: xiaomingxian  #github账号密码
          password: XIan_934792834