#------------------端口，路径-------------
server:
  port: 6666
  servlet:
    context-path: /mybatisPlus
#  -----------------数据源 ----------------
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_learn?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: abc
#  ----------------  mybatis-plus----------------
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #---entity location-
  type-aliases-package: com.mybatis_plus.pojo
#----------------logger ----------------
logging:
  level:
    com:
    xsy:
    sbmp:
    springbmp:
    dao: debug


