#------------------ eureka 高可用环境  ----------------
spring:
  application:
    name: client_jpa
eureka:
  instance:
    hostname: client_jpa
    #    将自己的ip注入到eureka中
  #    prefer-ip-address: true
  #    ip-address: ${IP_ADDRESS:127.0.0.1}
  #    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
#      hosts文件中配置的情况下这样使用
#      defaultZone: http://eureka02:8888/learn/eureka,http://eureka01:7777/learn/eureka
      defaultZone: http://localhost:8888/learn/eureka,http://localhost:7777/learn/eureka,http://localhost:6666/learn/eureka
      register-with-eureka: true
      fetch-registry: false
    server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 6000
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间


